config/routes.rb
Rails.application.routes.draw do
  get 'config/index'

  get 'graficos/index'

  get 'nube/index'

  get 'historico/index'

  #get 'cal_unoydos/prueba'

  #get 'indicadores/prueba_indicadores'

  resources :indicadoresacumulados
  resources :indicadoresdiarios
  resources :respuesta
  resources :encuesta
  resources :motivos
  resources :pregunta
  resources :pagos
  resources :mdps
  resources :lineas
  resources :contratos
  resources :fijomovils
  resources :segmentos
  resources :clientess
  resources :cal_unoydos
  resources :historico
  resources :nube
  resources :config
  resources :graficos
  #get 'welcome/index'
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see 	
end

app/models/atravesde.rb
class Atravesde < ApplicationRecord
  belongs_to :pago
  belongs_to :mdp
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :lineas
before_create :set_id_cliente
def set_id_cliente
	last_id_cliente = Cliente.maximum(:id_cliente)
	self.id_cliente = last_id_cliente.to_i + 1
end

end

app/models/contestum.rb
class Contestum < ApplicationRecord
  belongs_to :linea
  belongs_to :encuesta
end

app/models/contiene.rb
class Contiene < ApplicationRecord
  belongs_to :encuestum
  belongs_to :preguntum
end

app/models/contrato.rb
class Contrato < ApplicationRecord
	has_many :lineas
before_create :set_id_contrato
def set_id_contrato
	last_id_contrato = Contrato.maximum(:id_contrato)
	self.id_contrato = last_id_contrato.to_i + 1
end

end

app/models/contratum.rb
class Contratum < ApplicationRecord
  belongs_to :cliente
  belongs_to :linea
end

app/models/e.rb
class E < ApplicationRecord
  belongs_to :fijomovil
  belongs_to :linea
end

app/models/encuestum.rb
class Encuestum < ApplicationRecord
  belongs_to :linea
  has_many :pregunta, through: :respuesta
has_many :respuesta
has_and_belongs_to_many :motivos
before_create :set_id_encuesta
def set_id_encuesta
	last_id_encuesta = Encuestum.maximum(:id_encuesta)
	self.id_encuesta = last_id_encuesta.to_i + 1
end

end

app/models/es2.rb
class Es2 < ApplicationRecord
  belongs_to :contrato
  belongs_to :linea
end

app/models/fijomovil.rb
class Fijomovil < ApplicationRecord
	has_many :lineas
before_create :set_id_fijomovil
def set_id_fijomovil
	last_id_fijomovil = Fijomovil.maximum(:id_fijomovil)
	self.id_fijomovil = last_id_fijomovil.to_i + 1
end

end

app/models/linea.rb
class Linea < ApplicationRecord
  belongs_to :cliente
  belongs_to :segmento
  belongs_to :fijomovil
  belongs_to :contrato
  has_many :encuesta
before_create :set_id_linea
def set_id_linea
	last_id_linea = Linea.maximum(:id_linea)
	self.id_linea = last_id_linea.to_i + 1
end
end

app/models/mdp.rb
class Mdp < ApplicationRecord
	has_and_belongs_to_many :pagos
before_create :set_id_mdp
def set_id_mdp
	last_id_mdp = Mdp.maximum(:id_mdp)
	self.id_mdp = last_id_mdp.to_i + 1
end

end

app/models/motivo.rb
class Motivo < ApplicationRecord
	has_and_belongs_to_many :encuesta
before_create :set_id_motivo
def set_id_motivo
	last_id_motivo = Motivo.maximum(:id_motivo)
	self.id_motivo = last_id_motivo.to_i + 1
end

end

app/models/pago.rb
class Pago < ApplicationRecord
  belongs_to :linea
  has_and_belongs_to_many :mdps
before_create :set_id_pago
def set_id_pago
	last_id_pago = Pago.maximum(:id_pago)
	self.id_pago = last_id_pago.to_i + 1
end
end

app/models/preguntum.rb
class Preguntum < ApplicationRecord
	has_many :encuesta, through: :respuesta
has_many :respuesta
before_create :set_id_pregunta
def set_id_pregunta
	last_id_pregunta = Preguntum.maximum(:id_pregunta)
	self.id_pregunta = last_id_pregunta.to_i + 1
end

end

app/models/realiza.rb
class Realiza < ApplicationRecord
  belongs_to :linea
  belongs_to :pago
end

app/models/respuestum.rb
class Respuestum < ApplicationRecord
  belongs_to :preguntum
  belongs_to :encuestum
end

app/models/segmento.rb
class Segmento < ApplicationRecord
	has_many :lineas
before_create :set_id_segmento
def set_id_segmento
	last_id_segmento = Segmento.maximum(:id_segmento)
	self.id_segmento = last_id_segmento.to_i + 1
end

end

app/models/separa.rb
class Separa < ApplicationRecord
  belongs_to :segmento
  belongs_to :linea
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/motivos_controller.rb
class MotivosController < ApplicationController
  before_action :set_motivo, only: [:show, :edit, :update, :destroy]

  # GET /motivos
  # GET /motivos.json
  def index
    @motivos = Motivo.all
  end

  # GET /motivos/1
  # GET /motivos/1.json
  def show
  end

  # GET /motivos/new
  def new
    @motivo = Motivo.new
  end

  # GET /motivos/1/edit
  def edit
  end

  # POST /motivos
  # POST /motivos.json
  def create
    @motivo = Motivo.new(motivo_params)

    respond_to do |format|
      if @motivo.save
        format.html { redirect_to @motivo, notice: 'Motivo was successfully created.' }
        format.json { render :show, status: :created, location: @motivo }
      else
        format.html { render :new }
        format.json { render json: @motivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motivos/1
  # PATCH/PUT /motivos/1.json
  def update
    respond_to do |format|
      if @motivo.update(motivo_params)
        format.html { redirect_to @motivo, notice: 'Motivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @motivo }
      else
        format.html { render :edit }
        format.json { render json: @motivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motivos/1
  # DELETE /motivos/1.json
  def destroy
    @motivo.destroy
    respond_to do |format|
      format.html { redirect_to motivos_url, notice: 'Motivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motivo
      @motivo = Motivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motivo_params
      params.require(:motivo).permit(:id_motivo, :tipo_motivo)
    end
end

app/helpers/es_helper.rb
module EsHelper
end

app/helpers/motivos_helper.rb
module MotivosHelper
end

app/views/motivos/_form.html.erb
<%= form_for(motivo) do |f| %>
  <% if motivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(motivo.errors.count, "error") %> prohibited this motivo from being saved:</h2>

      <ul>
      <% motivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_motivo %>
    <%= f.number_field :id_motivo %>
  </div>

  <div class="field">
    <%= f.label :tipo_motivo %>
    <%= f.text_field :tipo_motivo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/motivos/edit.html.erb
<h1>Editing Motivo</h1>

<%= render 'form', motivo: @motivo %>

<%= link_to 'Show', @motivo %> |
<%= link_to 'Back', motivos_path %>

app/views/motivos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Motivos</h1>

<table>
  <thead>
    <tr>
      <th>Id motivo</th>
      <th>Tipo motivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motivos.each do |motivo| %>
      <tr>
        <td><%= motivo.id_motivo %></td>
        <td><%= motivo.tipo_motivo %></td>
        <td><%= link_to 'Show', motivo %></td>
        <td><%= link_to 'Edit', edit_motivo_path(motivo) %></td>
        <td><%= link_to 'Destroy', motivo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motivo', new_motivo_path %>

app/views/motivos/new.html.erb
<h1>New Motivo</h1>

<%= render 'form', motivo: @motivo %>

<%= link_to 'Back', motivos_path %>

app/views/motivos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id motivo:</strong>
  <%= @motivo.id_motivo %>
</p>

<p>
  <strong>Tipo motivo:</strong>
  <%= @motivo.tipo_motivo %>
</p>

<%= link_to 'Edit', edit_motivo_path(@motivo) %> |
<%= link_to 'Back', motivos_path %>