config/routes.rb
Rails.application.routes.draw do
  get 'config/index'

  get 'graficos/index'

  get 'nube/index'

  get 'historico/index'

  #get 'cal_unoydos/prueba'

  #get 'indicadores/prueba_indicadores'

  resources :indicadoresacumulados
  resources :indicadoresdiarios
  resources :respuesta
  resources :encuesta
  resources :motivos
  resources :pregunta
  resources :pagos
  resources :mdps
  resources :lineas
  resources :contratos
  resources :fijomovils
  resources :segmentos
  resources :clientess
  resources :cal_unoydos
  resources :historico
  resources :nube
  resources :config
  resources :graficos
  #get 'welcome/index'
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see 	
end

app/models/atravesde.rb
class Atravesde < ApplicationRecord
  belongs_to :pago
  belongs_to :mdp
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :lineas
before_create :set_id_cliente
def set_id_cliente
	last_id_cliente = Cliente.maximum(:id_cliente)
	self.id_cliente = last_id_cliente.to_i + 1
end

end

app/models/contestum.rb
class Contestum < ApplicationRecord
  belongs_to :linea
  belongs_to :encuesta
end

app/models/contiene.rb
class Contiene < ApplicationRecord
  belongs_to :encuestum
  belongs_to :preguntum
end

app/models/contrato.rb
class Contrato < ApplicationRecord
	has_many :lineas
before_create :set_id_contrato
def set_id_contrato
	last_id_contrato = Contrato.maximum(:id_contrato)
	self.id_contrato = last_id_contrato.to_i + 1
end

end

app/models/contratum.rb
class Contratum < ApplicationRecord
  belongs_to :cliente
  belongs_to :linea
end

app/models/e.rb
class E < ApplicationRecord
  belongs_to :fijomovil
  belongs_to :linea
end

app/models/encuestum.rb
class Encuestum < ApplicationRecord
  belongs_to :linea
  has_many :pregunta, through: :respuesta
has_many :respuesta
has_and_belongs_to_many :motivos
before_create :set_id_encuesta
def set_id_encuesta
	last_id_encuesta = Encuestum.maximum(:id_encuesta)
	self.id_encuesta = last_id_encuesta.to_i + 1
end

end

app/models/es2.rb
class Es2 < ApplicationRecord
  belongs_to :contrato
  belongs_to :linea
end

app/models/fijomovil.rb
class Fijomovil < ApplicationRecord
	has_many :lineas
before_create :set_id_fijomovil
def set_id_fijomovil
	last_id_fijomovil = Fijomovil.maximum(:id_fijomovil)
	self.id_fijomovil = last_id_fijomovil.to_i + 1
end

end

app/models/linea.rb
class Linea < ApplicationRecord
  belongs_to :cliente
  belongs_to :segmento
  belongs_to :fijomovil
  belongs_to :contrato
  has_many :encuesta
before_create :set_id_linea
def set_id_linea
	last_id_linea = Linea.maximum(:id_linea)
	self.id_linea = last_id_linea.to_i + 1
end
end

app/models/mdp.rb
class Mdp < ApplicationRecord
	has_and_belongs_to_many :pagos
before_create :set_id_mdp
def set_id_mdp
	last_id_mdp = Mdp.maximum(:id_mdp)
	self.id_mdp = last_id_mdp.to_i + 1
end

end

app/models/motivo.rb
class Motivo < ApplicationRecord
	has_and_belongs_to_many :encuesta
before_create :set_id_motivo
def set_id_motivo
	last_id_motivo = Motivo.maximum(:id_motivo)
	self.id_motivo = last_id_motivo.to_i + 1
end

end

app/models/pago.rb
class Pago < ApplicationRecord
  belongs_to :linea
  has_and_belongs_to_many :mdps
before_create :set_id_pago
def set_id_pago
	last_id_pago = Pago.maximum(:id_pago)
	self.id_pago = last_id_pago.to_i + 1
end
end

app/models/preguntum.rb
class Preguntum < ApplicationRecord
	has_many :encuesta, through: :respuesta
has_many :respuesta
before_create :set_id_pregunta
def set_id_pregunta
	last_id_pregunta = Preguntum.maximum(:id_pregunta)
	self.id_pregunta = last_id_pregunta.to_i + 1
end

end

app/models/realiza.rb
class Realiza < ApplicationRecord
  belongs_to :linea
  belongs_to :pago
end

app/models/respuestum.rb
class Respuestum < ApplicationRecord
  belongs_to :preguntum
  belongs_to :encuestum
end

app/models/segmento.rb
class Segmento < ApplicationRecord
	has_many :lineas
before_create :set_id_segmento
def set_id_segmento
	last_id_segmento = Segmento.maximum(:id_segmento)
	self.id_segmento = last_id_segmento.to_i + 1
end

end

app/models/separa.rb
class Separa < ApplicationRecord
  belongs_to :segmento
  belongs_to :linea
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/segmentos_controller.rb
class SegmentosController < ApplicationController
  before_action :set_segmento, only: [:show, :edit, :update, :destroy]

  # GET /segmentos
  # GET /segmentos.json
  def index
    @segmentos = Segmento.all
  end

  # GET /segmentos/1
  # GET /segmentos/1.json
  def show
  end

  # GET /segmentos/new
  def new
    @segmento = Segmento.new
  end

  # GET /segmentos/1/edit
  def edit
  end

  # POST /segmentos
  # POST /segmentos.json
  def create
    @segmento = Segmento.new(segmento_params)

    respond_to do |format|
      if @segmento.save
        format.html { redirect_to @segmento, notice: 'Segmento was successfully created.' }
        format.json { render :show, status: :created, location: @segmento }
      else
        format.html { render :new }
        format.json { render json: @segmento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segmentos/1
  # PATCH/PUT /segmentos/1.json
  def update
    respond_to do |format|
      if @segmento.update(segmento_params)
        format.html { redirect_to @segmento, notice: 'Segmento was successfully updated.' }
        format.json { render :show, status: :ok, location: @segmento }
      else
        format.html { render :edit }
        format.json { render json: @segmento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segmentos/1
  # DELETE /segmentos/1.json
  def destroy
    @segmento.destroy
    respond_to do |format|
      format.html { redirect_to segmentos_url, notice: 'Segmento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segmento
      @segmento = Segmento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segmento_params
      params.require(:segmento).permit(:id_segmento, :tipo_segmento)
    end
end

app/helpers/es_helper.rb
module EsHelper
end

app/helpers/segmentos_helper.rb
module SegmentosHelper
end

app/views/segmentos/_form.html.erb
<%= form_for(segmento) do |f| %>
  <% if segmento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(segmento.errors.count, "error") %> prohibited this segmento from being saved:</h2>

      <ul>
      <% segmento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_segmento %>
    <%= f.number_field :id_segmento %>
  </div>

  <div class="field">
    <%= f.label :tipo_segmento %>
    <%= f.text_field :tipo_segmento %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/segmentos/edit.html.erb
<h1>Editing Segmento</h1>

<%= render 'form', segmento: @segmento %>

<%= link_to 'Show', @segmento %> |
<%= link_to 'Back', segmentos_path %>

app/views/segmentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Segmentos</h1>

<table>
  <thead>
    <tr>
      <th>Id segmento</th>
      <th>Tipo segmento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @segmentos.each do |segmento| %>
      <tr>
        <td><%= segmento.id_segmento %></td>
        <td><%= segmento.tipo_segmento %></td>
        <td><%= link_to 'Show', segmento %></td>
        <td><%= link_to 'Edit', edit_segmento_path(segmento) %></td>
        <td><%= link_to 'Destroy', segmento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segmento', new_segmento_path %>

app/views/segmentos/new.html.erb
<h1>New Segmento</h1>

<%= render 'form', segmento: @segmento %>

<%= link_to 'Back', segmentos_path %>

app/views/segmentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id segmento:</strong>
  <%= @segmento.id_segmento %>
</p>

<p>
  <strong>Tipo segmento:</strong>
  <%= @segmento.tipo_segmento %>
</p>

<%= link_to 'Edit', edit_segmento_path(@segmento) %> |
<%= link_to 'Back', segmentos_path %>